//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossBowCreator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossBowCreator.ResourceDictionary", typeof(ResourceDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.11 0.645 0.0200000000000002
        ///0.11 0.645 0.0800000000000001
        ///0.11 0.630764952519361 0.0781259204458988
        ///0.11 0.6175 0.0726313972081442
        ///0.11 0.60610912703474 0.0638908729652602
        ///0.11 0.597368602791856 0.0525
        ///0.11 0.591874079554101 0.0392350474806387
        ///0.11 0.59 0.025
        ///0.11 0.59 0.0
        ///0.11 1.35 0.0
        ///0.11 1.35 0.0200000000000002
        ///normal
        ///1.0 0.0 0.0
        ///spine
        ///0.11 0.645 0.0200000000000002
        ///0.05 0.645 0.0200000000000001
        ///.
        /// </summary>
        public static string ArrowBaseAboveBody {
            get {
                return ResourceManager.GetString("ArrowBaseAboveBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.0510222252113279 0.645 0.0277645713530755
        ///0.05 0.645 0.0199999999999999
        ///0.08 0.645 0.02
        ///0.11 0.645 0.0200000000000002
        ///0.108977774788672 0.645 0.0277645713530758
        ///0.105980762113533 0.645 0.0350000000000001
        ///0.101213203435596 0.645 0.0412132034355965
        ///0.0949999999999999 0.645 0.0459807621135332
        ///0.0877645713530755 0.645 0.0489777747886721
        ///0.0799999999999998 0.645 0.05
        ///0.0722354286469242 0.645 0.048977774788672
        ///0.0649999999999999 0.645 0.0459807621135331
        ///0.0587867965644035 0.645 0.0412132034355 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ArrowCylinder {
            get {
                return ResourceManager.GetString("ArrowCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.716314003682517 0.891576916113173 -0.0696453832733847
        ///0.715241748012182 0.890754145399312 -0.0800000000000002
        ///0.716314003682517 0.891576916113173 -0.0903546167266154
        ///0.719460249842172 0.893991115702301 -0.100011415083128
        ///0.724472284902363 0.897836985468683 -0.10831562667121
        ///0.73101485412952 0.902857275407401 -0.114698167168035
        ///0.738644792509767 0.908711933043181 -0.118716168944825
        ///0.746839560914019 0.915000000000001 -0.120087778702577
        ///0.755034329318272 0.921288066956821 -0.118716168944825
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BigArc {
            get {
                return ResourceManager.GetString("BigArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.16 1.35 0.0
        ///0.16 0.0 0.0
        ///0.16 0.0 -0.23
        ///0.16 0.45 -0.16
        ///0.16 1.35 -0.16
        ///normal
        ///1.0 0.0 0.0
        ///spine
        ///0.16 0.0 0.0
        ///0.0 0.0 0.0
        ///.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.12 0.599282032302755 -0.46
        ///0.136568542494924 0.586568542494924 -0.46
        ///0.149282032302755 0.57 -0.46
        ///0.157274066103126 0.550705523608202 -0.46
        ///0.16 0.53 -0.46
        ///0.157274066103126 0.509294476391798 -0.46
        ///0.149282032302755 0.49 -0.46
        ///0.136568542494924 0.473431457505076 -0.46
        ///0.12 0.460717967697245 -0.46
        ///0.100705523608202 0.452725933896875 -0.46
        ///0.08 0.45 -0.46
        ///0.0592944763917983 0.452725933896875 -0.46
        ///0.04 0.460717967697245 -0.46
        ///0.0234314575050762 0.473431457505076 -0.46
        ///0.0107179676972449  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BottomCylinder {
            get {
                return ResourceManager.GetString("BottomCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.08 1.39776457135308 -0.0810222252113281
        ///0.08 1.405 -0.084019237886467
        ///0.08 1.4112132034356 -0.0887867965644037
        ///0.08 1.41598076211353 -0.0950000000000001
        ///0.08 1.41897777478867 -0.102235428646925
        ///0.08 1.42 -0.11
        ///0.08 1.41897777478867 -0.117764571353076
        ///0.08 1.41598076211353 -0.125
        ///0.08 1.4112132034356 -0.131213203435597
        ///0.08 1.405 -0.135980762113533
        ///0.08 1.39776457135308 -0.138977774788672
        ///0.08 1.39 -0.14
        ///0.08 1.38223542864692 -0.138977774788672
        ///0.08 1.375 -0.135980762113533
        ///0.08 1.36878 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FrontTorus {
            get {
                return ResourceManager.GetString("FrontTorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///-0.529137849492211 1.00196512616507 -0.0800000000000001
        ///-0.52848077579206 1.00274819610782 -0.0722354286469245
        ///-0.526554333178407 1.00504404101357 -0.0650000000000002
        ///-0.523489805531776 1.00869620284605 -0.0587867965644037
        ///-0.519496035346913 1.01345579281185 -0.054019237886467
        ///-0.514845191461899 1.01899845272041 -0.0510222252113281
        ///-0.509854221201615 1.02494645945864 -0.0500000000000001
        ///-0.504863250941331 1.03089446619686 -0.0510222252113281
        ///-0.500212407056317 1.03643712610542 -0.0540192378864 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeftCylinder {
            get {
                return ResourceManager.GetString("LeftCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.08 1.487639320225 -0.16
        ///0.148819660112501 1.35 -0.16
        ///0.0111803398874991 1.35 -0.16
        ///normal
        ///0.0 0.0 -1.0
        ///spine
        ///0.08 1.487639320225 -0.16
        ///0.08 1.487639320225 -0.0800000000000001
        ///.
        /// </summary>
        public static string LowerFrontTriangle {
            get {
                return ResourceManager.GetString("LowerFrontTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.68848077579206 1.00274819610782 -0.0722354286469245
        ///0.689137849492211 1.00196512616507 -0.0800000000000001
        ///0.68848077579206 1.00274819610782 -0.0877645713530757
        ///0.686554333178407 1.00504404101357 -0.0950000000000001
        ///0.683489805531776 1.00869620284605 -0.101213203435596
        ///0.679496035346913 1.01345579281185 -0.105980762113533
        ///0.674845191461899 1.01899845272041 -0.108977774788672
        ///0.669854221201615 1.02494645945864 -0.11
        ///0.664863250941331 1.03089446619686 -0.108977774788672
        ///0.660212407056316 1.03 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RightCylinder {
            get {
                return ResourceManager.GetString("RightCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to face
        ///0.16 1.35 0.02
        ///0.08 1.51 0.02
        ///0.0 1.35 0.02
        ///normal
        ///0.0 0.0 1.0
        ///spine
        ///0.08 1.51 0.02
        ///0.08 1.51 -0.0800000000000001
        ///.
        /// </summary>
        public static string UpperFrontTriangle {
            get {
                return ResourceManager.GetString("UpperFrontTriangle", resourceCulture);
            }
        }
    }
}
